"""
Integration tests for the FFmpeg contrib package.

These exercise real `ffmpeg`/`ffprobe` binaries against a tiny
synthetic video generated on the fly (via ffmpeg's `lavfi testsrc`),
rather than mocking subprocess -- this is the proof that SceneForge's
Media -> [enrich] -> Provider -> Artifact contract actually holds up
against a real external tool, not just against stubs.

Skipped automatically (not failed) on any machine without ffmpeg on
PATH, so the rest of the suite stays runnable everywhere.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

from sceneforge.contrib.ffmpeg import FFmpegFrameExtractionProvider, FFprobeEnricher
from sceneforge.core.artifact import ArtifactKind
from sceneforge.core.pipeline import Pipeline
from sceneforge.core.storage import InMemoryArtifactStore
from sceneforge.media.video_loader import LocalVideoLoader

FFMPEG_AVAILABLE = (
    shutil.which("ffmpeg") is not None and shutil.which("ffprobe") is not None
)

pytestmark = pytest.mark.skipif(
    not FFMPEG_AVAILABLE, reason="ffmpeg/ffprobe not available on PATH"
)


@pytest.fixture
def synthetic_video(tmp_path: Path) -> Path:
    """A real, tiny (2s, 10fps, 64x64) H.264 video generated by ffmpeg itself."""
    path = tmp_path / "synthetic.mp4"
    subprocess.run(
        [
            "ffmpeg",
            "-y",
            "-f",
            "lavfi",
            "-i",
            "testsrc=duration=2:size=64x64:rate=10",
            "-pix_fmt",
            "yuv420p",
            str(path),
        ],
        capture_output=True,
        check=True,
        timeout=30,
    )
    return path


def test_local_video_loader_produces_placeholder_metadata(synthetic_video: Path):
    """Sanity check on the documented pre-enrichment state we're fixing."""
    media = LocalVideoLoader(synthetic_video).load()

    assert media.duration == 0.0
    assert media.codec == "unknown"
    assert media.fps == 0.0
    assert media.metadata["source"] == str(synthetic_video)


def test_ffprobe_enricher_fills_in_real_metadata(synthetic_video: Path):
    media = LocalVideoLoader(synthetic_video).load()
    enriched = FFprobeEnricher().enrich(media)

    assert enriched is not media
    assert enriched.id == media.id  # same logical media, corrected facts
    assert 1.5 <= enriched.duration <= 2.5
    assert enriched.codec in ("h264", "libx264")
    assert 5.0 <= enriched.fps <= 15.0
    assert enriched.metadata["width"] == 64
    assert enriched.metadata["height"] == 64


def test_frame_extraction_provider_writes_real_frames(
    synthetic_video: Path, tmp_path: Path
):
    output_dir = tmp_path / "frames"
    media = LocalVideoLoader(synthetic_video).load()
    enriched = FFprobeEnricher().enrich(media)

    provider = FFmpegFrameExtractionProvider(frame_count=3, output_dir=output_dir)
    artifacts = provider.run(enriched)

    assert len(artifacts) == 3
    for artifact in artifacts:
        assert artifact.kind == ArtifactKind.FRAME
        frame_file = Path(artifact.frame_path)
        assert frame_file.exists()
        assert frame_file.stat().st_size > 0


def test_full_pipeline_with_enricher_and_real_provider(
    synthetic_video: Path, tmp_path: Path
):
    """
    The end-to-end proof: LocalVideoLoader -> Pipeline(enricher=FFprobeEnricher)
    -> FFmpegFrameExtractionProvider -> real PNG frames on disk, driven
    entirely through the public Pipeline API.
    """
    media = LocalVideoLoader(synthetic_video).load()
    output_dir = tmp_path / "pipeline_frames"

    pipeline = Pipeline(
        provider=FFmpegFrameExtractionProvider(frame_count=2, output_dir=output_dir),
        enricher=FFprobeEnricher(),
    )

    result = pipeline.run_detailed(media)

    assert len(result.artifacts) == 2
    assert result.media.duration > 0  # proves enrichment ran before the provider
    for artifact in result.artifacts:
        assert Path(artifact.frame_path).exists()


def test_pipeline_caches_frame_extraction_results(
    synthetic_video: Path, tmp_path: Path
):
    media = LocalVideoLoader(synthetic_video).load()
    store = InMemoryArtifactStore()
    output_dir = tmp_path / "cached_frames"

    pipeline = Pipeline(
        provider=FFmpegFrameExtractionProvider(frame_count=2, output_dir=output_dir),
        enricher=FFprobeEnricher(),
        store=store,
    )

    first = pipeline.run_detailed(media)
    second = pipeline.run_detailed(media)

    assert first.from_cache is False
    assert second.from_cache is True
    second_paths = [a.frame_path for a in second.artifacts]
    first_paths = [a.frame_path for a in first.artifacts]
    assert second_paths == first_paths
